# This is only an example configuration file for the Hive CLI,
# but you can use it as a template for your own configuration.
# TODO: in the future, we'll generate it automatically with `hive init`.

project_name: llm-speedrun
coordinator_config_name: default-coordinator-config
platform: k8s
repo:
  url: https://github.com/hiverge/llm-speedrun-project.git
  branch: main
  evaluation_script: cifar10-94-630/evaluator.py
sandbox:
  # image will be set automatically after building the image
  # image: <>
  replicas: 3
  timeout: 120
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "2"
      memory: "2Gi"
dashboard:
  enabled: false
wandb:
  enabled: false
# cloud vendor configuration
gcp:
  enabled: true
  project_id: runsandbox-449400
