# This is only an example configuration file for the Hive CLI,
# but you can use it as a template for your own configuration.
# TODO: in the future, we'll generate it automatically with `hive init`.

project_name: beluga-direct-plan-project
coordinator_config_name: default-coordinator-config
platform: k8s
repo:
  address: https://github.com/hiverge/beluga-direct-plan-project.git
sandbox:
  # image will be set automatically after building the image
  # image: <>
  replicas: 1
  timeout: 60
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
wandb:
  enabled: false
# cloud vendor configuration
gcp:
  enabled: true
  project_id: runsandbox-449400
