# The minimum configuration for Hive CLI.

project_name: beluga-direct-plan-project
repo:
  url: https://github.com/hiverge/beluga-direct-plan-project.git
  evolve_files_and_ranges: main.py
sandbox:
  replicas: 1
# cloud vendor configuration
gcp:
  enabled: true
  project_id: runsandbox-449400
