# This is only an example configuration file for the Hive CLI.

project_name: demo-project
token_path: /Desktop/HivergeAI/hive.kubeconfig
coordinator_config_name: default-coordinator-config
platform: k8s
repo:
  url: https://github.com/hiverge/demo-project.git
  branch: main
  evaluation_script: evaluator.py
  evolve_files_and_ranges: main.py
sandbox:
  replicas: 3
  timeout: 1800
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "2"
      memory: "2Gi"
    shmsize: "1Gi"
    accelerators: a100-40gb:1 # or a100-80gb:8 or h100:8
  pre_processor: |
    print("Running pre-processing script...")
  envs:
    - name: <key>
      value: <value>
dashboard:
  frontend_image: <image-name>
  backend_image: <image-name>
wandb:
  enabled: false
# cloud vendor configuration
cloud_provider:
  spot: true
  gcp:
    enabled: true
  aws:
    enabled: false
