[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "hive-cli"
version = "0.0.1"
authors = [
  { name="Hive", email="hive@hiverage.ai" },
]
description = "Hive CLI for managing Hive"
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
    "PyYAML>=5.1",
    "pydantic>=1.8.2",
    "gitpython>=3.1.24",
    "rich>=12.5.1",
    "kubernetes>=32.0.0",
]

[project.optional-dependencies]
test = [
  "pytest>=6.2.4",
  "flask==2.3.3",
  "requests",
  "psutil",
]
dev = [
  "ruff>=0.12",
]

[project.scripts]
hive = "hive_cli.main:main"

[tool.ruff]
line-length = 100
exclude = ["libs"]

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = ["E501"]

[tool.ruff.format]
quote-style = "double"
