name: Python CI

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: yezz123/setup-uv@v4

      - name: Install dependencies
        run: uv pip install -e .

      - name: Lint
        run: make lint
